{% set version = "0.15.1" %}

package:
  name: arrow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arrow/arrow-{{ version }}.tar.gz
  sha256: c65ea9214403c77b09bd676cba3dcf1e0a396f5dfb316b811bb7f7e10d99e955

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - python-dateutil
    - backports.functools_lru_cache  # [py27]
  run:
    - python
    - python-dateutil
    - backports.functools_lru_cache  # [py27]

test:
  source_files:
    - tests
  requires:
    - nose
    - chai
    - simplejson
    - pytz
    - mock
  commands:
    - nosetests

about:
  home: https://github.com/crsmithdev/arrow
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Better dates & times for Python'
  description: |
    Arrow is a Python library that offers a sensible, human-friendly approach to
    creating, manipulating, formatting and converting dates, times, and timestamps.
    It implements and updates the datetime type, plugging gaps in functionality,
    and provides an intelligent module API that supports many common creation
    scenarios. Simply put, it helps you work with dates and times with fewer
    imports and a lot less code.
  dev_url: https://github.com/crsmithdev/arrow
  doc_url: https://arrow.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
