{% set version = "0.14.7" %}

package:
  name: arrow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arrow/arrow-{{ version }}.tar.gz
  sha256: 67f8be7c0cf420424bc62d8d7dc40b44e4bb2f7b515f9cc2954fb36e35797656

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - python-dateutil
    - backports.functools_lru_cache  # [py27]
  run:
    - python
    - python-dateutil
    - backports.functools_lru_cache  # [py27]

test:
  source_files:
    - tests
  requires:
    - nose
    - chai
    - simplejson
    - pytz
    - mock
  commands:
    - nosetests

about:
  home: https://github.com/crsmithdev/arrow
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Better dates & times for Python'
  description: |
    Arrow is a Python library that offers a sensible, human-friendly approach to
    creating, manipulating, formatting and converting dates, times, and timestamps.
    It implements and updates the datetime type, plugging gaps in functionality,
    and provides an intelligent module API that supports many common creation
    scenarios. Simply put, it helps you work with dates and times with fewer
    imports and a lot less code.
  dev_url: https://github.com/crsmithdev/arrow
  doc_url: https://arrow.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
